[package]
name = "InterestLST"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "testnet-v1.10.1" }
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.10.1" }
SuiSystem = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-system", rev = "testnet-v1.10.1" }
Access = { local = "../access" }
InterestFramework = { local = "../framework" }
InterestTokens = { local = "../tokens" }

[addresses]
interest_lst = "0x0"
std = "0x1"
sui = "0x2"
sui_system = "0x3"